version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.14
    steps:
      - checkout
      - run: sudo npm install --global web-ext
      - run: echo $CIRCLE_BUILD_NUM
      - run: sed -i 's/1.0.0/1.0.${CIRCLE_BUILD_NUM}/g' manifest.json
      - run: web-ext sign --api-key $FIREFOX_KEY --api-secret $FIREFOX_SECRET