version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.14
    
    steps:
      - checkout
      - run: 
          name: Install Mozilla web-ext.
          command: sudo npm install --global web-ext
      - run: 
          name: Build and sign extension.
          command: web-ext sign --api-key $FIREFOX_KEY --api-secret $FIREFOX_SECRET
          environment:
            FIREFOX_KEY: firefox_key
            FIREFOX_SECRET: firefox_secret
