version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.14
    steps:
      - checkout
      - run: sudo npm install --global web-ext
      - run: web-ext sign --api-key $FIREFOX_KEY --api-secret $FIREFOX_SECRET
